import { useState, useRef } from 'react'
import { useNavigate } from 'react-router-dom'
import { uploadDocument } from '../lib/api'

export default function UploadPage() {
  const [dragging, setDragging] = useState(false)
  const [file, setFile] = useState(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const inputRef = useRef()
  
  const navigate = useNavigate()

  const maxCards = estimateMaxCards(file)

  const handleFile = (f) => {
    if (!f) return
    const allowed = ['application/pdf',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'text/plain']
    if (!allowed.includes(f.type)) {
      alert('Please upload a PDF, DOCX, or TXT file.')
      return
    }
    setFile(f)
    setCardCount(Math.min(10, estimateMaxCards(f)))
  }

  const handleDrop = (e) => {
    e.preventDefault()
    setDragging(false)
    handleFile(e.dataTransfer.files[0])
  }

  const handleGenerate = async () => {
    if (!file) return
    setLoading(true)
    setError('')

    try {
      const result = await uploadDocument({ file })
      navigate(`/deck/${result.deck.id}`)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to generate flashcards.')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="fade-up" style={{ maxWidth: '600px', margin: '0 auto', paddingTop: '40px' }}>

      <h1 style={{
        fontFamily: 'Syne, sans-serif',
        fontWeight: 800,
        fontSize: '36px',
        letterSpacing: '-0.03em',
        lineHeight: 1.1,
        marginBottom: '10px',
      }}>
        Upload your notes.<br />
        <span style={{ color: 'var(--accent)' }}>Get flashcards.</span>
      </h1>

      <p style={{ color: 'var(--text-muted)', marginBottom: '40px', fontSize: '14px' }}>
        Supports PDF, DOCX, and plain text. Cards are generated by the backend and saved automatically.
      </p>

      {/* Drop Zone */}
      <div
        onDragOver={(e) => { e.preventDefault(); setDragging(true) }}
        onDragLeave={() => setDragging(false)}
        onDrop={handleDrop}
        onClick={() => inputRef.current.click()}
        style={{
          border: `1.5px dashed ${dragging ? 'var(--accent)' : file ? '#2d4a1e' : 'var(--border-hi)'}`,
          borderRadius: 'var(--radius)',
          background: dragging ? '#111a09' : file ? '#0c160a' : 'var(--bg-card)',
          padding: '56px 32px',
          textAlign: 'center',
          cursor: 'pointer',
          transition: 'all 0.2s',
          marginBottom: '20px',
        }}
      >
        <input
          ref={inputRef}
          type="file"
          accept=".pdf,.docx,.txt"
          style={{ display: 'none' }}
          onChange={e => handleFile(e.target.files[0])}
        />

        {file ? (
          <>
            <div style={{
              width: '40px', height: '40px', borderRadius: '8px',
              background: '#1a3d12', border: '1px solid #2d5a1e',
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              margin: '0 auto 14px', fontSize: '20px',
            }}>📄</div>
            <p style={{ fontWeight: 500, color: 'var(--text)', marginBottom: '4px' }}>{file.name}</p>
            <p style={{ fontSize: '12px', color: 'var(--text-muted)' }}>
              {(file.size / 1024).toFixed(1)} KB · click to replace
            </p>
          </>
        ) : (
          <>
            <div style={{
              width: '40px', height: '40px', borderRadius: '8px',
              background: 'var(--border)', display: 'flex',
              alignItems: 'center', justifyContent: 'center',
              margin: '0 auto 14px', fontSize: '20px',
            }}>↑</div>
            <p style={{ fontWeight: 500, marginBottom: '4px' }}>
              {dragging ? 'Drop it here' : 'Drag & drop your file'}
            </p>
            <p style={{ fontSize: '12px', color: 'var(--text-muted)' }}>
              or click to browse · PDF, DOCX, TXT
            </p>
          </>
        )}
      </div>

      {/* Card count selector — only shown once a file is picked */}
      {file && (
        <div style={{
          background: 'var(--bg-card)',
          border: '1px solid var(--border)',
          borderRadius: 'var(--radius)',
          padding: '20px 24px',
          marginBottom: '20px',
        }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '12px' }}>
            <span style={{ fontSize: '13px', fontWeight: 500 }}>Number of flashcards</span>
            <span style={{
              fontFamily: 'Syne, sans-serif',
              fontWeight: 700,
              fontSize: '20px',
              color: 'var(--accent)',
            }}>{cardCount}</span>
          </div>

          <input
            type="range"
            min={3}
            max={maxCards || 3}
            value={cardCount}
            onChange={e => setCardCount(Number(e.target.value))}
            style={{ width: '100%', accentColor: 'var(--accent)', cursor: 'pointer' }}
          />

          <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: '8px' }}>
            <span style={{ fontSize: '11px', color: 'var(--text-muted)' }}>3 min</span>
            <span style={{ fontSize: '11px', color: 'var(--text-muted)' }}>
              ~{maxCards} estimated max from this file
            </span>
            <span style={{ fontSize: '11px', color: 'var(--text-muted)' }}>{maxCards} max</span>
          </div>
        </div>
      )}

      {/* Generate Button */}
      <button
        onClick={handleGenerate}
        disabled={!file || loading}
        style={{
          width: '100%',
          padding: '14px',
          borderRadius: 'var(--radius)',
          border: 'none',
          background: file ? 'var(--accent)' : 'var(--border)',
          color: file ? 'var(--bg)' : 'var(--text-muted)',
          fontFamily: 'Syne, sans-serif',
          fontWeight: 700,
          fontSize: '15px',
          letterSpacing: '-0.01em',
          cursor: file ? 'pointer' : 'not-allowed',
          transition: 'all 0.2s',
          opacity: loading ? 0.7 : 1,
        }}
      >
        {loading ? `Generating ${cardCount} flashcards...` : `Generate ${file ? cardCount : ''} flashcards →`}
      </button>

      {error ? (
        <p style={{ color: 'var(--hard)', fontSize: '13px', marginTop: '14px', textAlign: 'center' }}>
          {error}
        </p>
      ) : null}

    </div>
  )
}